# Generated by Django 5.2.12 on 2026-04-03 01:41

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("carpool", "0011_alter_ride_payment_method"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Organization",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Name")),
                (
                    "email_domain",
                    models.CharField(
                        help_text="e.g. insa-rennes.fr — users with this domain are linked to this organization",
                        max_length=255,
                        unique=True,
                        verbose_name="Email domain",
                    ),
                ),
                (
                    "admins",
                    models.ManyToManyField(
                        blank=True,
                        related_name="administered_organizations",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Admins",
                    ),
                ),
            ],
            options={
                "verbose_name": "Organization",
                "verbose_name_plural": "Organizations",
            },
        ),
        migrations.CreateModel(
            name="OrganizationStatistics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("total_users", models.IntegerField(default=0)),
                ("total_rides", models.IntegerField(default=0)),
                ("total_distance", models.FloatField(default=0.0)),
                ("total_co2", models.FloatField(default=0.0)),
                (
                    "organization",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="statistics",
                        to="carpool.organization",
                    ),
                ),
            ],
            options={
                "verbose_name": "Organization statistic",
                "verbose_name_plural": "Organization statistics",
            },
        ),
        migrations.CreateModel(
            name="OrganizationMonthlyStatistics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "month",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(12),
                        ]
                    ),
                ),
                ("year", models.IntegerField()),
                ("total_users", models.IntegerField(default=0)),
                ("total_rides", models.IntegerField(default=0)),
                ("total_distance", models.FloatField(default=0.0)),
                ("total_co2", models.FloatField(default=0.0)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="monthly_statistics",
                        to="carpool.organization",
                    ),
                ),
            ],
            options={
                "verbose_name": "Organization monthly statistic",
                "verbose_name_plural": "Organization monthly statistics",
                "unique_together": {("organization", "month", "year")},
            },
        ),
    ]
